import { EventEmitter, AfterContentInit, ChangeDetectorRef, OnDestroy, QueryList, TemplateRef, ElementRef } from '@angular/core';
import { IDataTableColumn, IDataTablePaginationOptions, IDataTableSearchOptions, IDataTableService, IDataTablePreferences } from './interfaces';
import { DataTableSource } from './data-table.source';
import { NovoLabelService } from '../../services/novo-label-service';
import { DataTableState } from './state/data-table-state.service';
import { NovoTemplate } from '../common/novo-template/novo-template.directive';
export declare class NovoDataTable<T> implements AfterContentInit, OnDestroy {
    labels: NovoLabelService;
    private ref;
    state: DataTableState<T>;
    globalSearchHiddenClassToggle: boolean;
    customTemplates: QueryList<NovoTemplate>;
    defaultTemplates: QueryList<NovoTemplate>;
    novoDataTableContainer: ElementRef;
    resized: EventEmitter<IDataTableColumn<T>>;
    displayedColumns: string[];
    private _disabledColumns;
    paginationOptions: IDataTablePaginationOptions;
    searchOptions: IDataTableSearchOptions;
    defaultSort: {
        id: string;
        value: string;
    };
    name: string;
    rowIdentifier: string;
    trackByFn: Function;
    templates: {
        [key: string]: TemplateRef<any>;
    };
    fixedHeader: boolean;
    dataTableService: IDataTableService<T>;
    rows: T[];
    outsideFilter: EventEmitter<any>;
    refreshSubject: EventEmitter<any>;
    columns: IDataTableColumn<T>[];
    customFilter: boolean;
    private _customFilter;
    hasExandedRows: boolean;
    private _hasExandedRows;
    forceShowHeader: boolean;
    private _forceShowHeader;
    hideGlobalSearch: boolean;
    private _hideGlobalSearch;
    preferencesChanged: EventEmitter<IDataTablePreferences>;
    dataSource: DataTableSource<T>;
    loading: boolean;
    columnToTemplate: {
        [key: string]: TemplateRef<any>;
    };
    columnsLoaded: boolean;
    selection: Set<string>;
    scrollLeft: number;
    expandable: boolean;
    private outsideFilterSubscription;
    private refreshSubscription;
    private resetSubscription;
    private paginationSubscription;
    private _columns;
    private scrollListenerHandler;
    private initialized;
    readonly empty: boolean;
    readonly loadingClass: boolean;
    constructor(labels: NovoLabelService, ref: ChangeDetectorRef, state: DataTableState<T>);
    ngOnDestroy(): void;
    ngAfterContentInit(): void;
    onSearchChange(term: string): void;
    trackColumnsBy(index: number, item: IDataTableColumn<T>): string;
    isDisabled(check: any, row: T): boolean;
    isExpanded(row: T): boolean;
    expandRow(row: T): void;
    expandRows(expand: boolean): void;
    allCurrentRowsExpanded(): boolean;
    isSelected(row: T): boolean;
    selectRow(row: T): void;
    selectRows(selected: boolean): void;
    allCurrentRowsSelected(): boolean;
    private configureLastDisplayedColumn;
    private configureColumns;
    private scrollListener;
}
