/**
 * AUTOGENERATED FILE - DO NOT EDIT
 * Generated by: https://bhsource.bullhorn.com/DEV_WORKSPACE/country-state-parser
 * Last generated on: Wed Oct 10 2018 08:52:04 GMT-0500 (Central Daylight Time)
 */
export declare const COUNTRIES: {
    code: string;
    id: number;
    name: string;
    states: {
        code: string;
        name: string;
    }[];
}[];
/**
 * Gets all countries
 */
export declare function getCountries(): string[];
/**
 * Gets a country by country ID
 */
export declare function findByCountryId(id: number): object | undefined;
/**
 * Gets a country by country name
 * @param name - Name of country to find
 */
export declare function findByCountryName(name: string): object | undefined;
/**
 * Gets a country by country code
 * @param code - Code of country to find
 */
export declare function findByCountryCode(code: string): object | undefined;
/**
 * Gets states by country name
 * @param name - Name of the country to search by
 */
export declare function getStateObjects(name: string): any[];
/**
 * Gets state names by country name
 * @param name - Name of the country to search by
 */
export declare function getStates(name: string): string[];
