import { OnDestroy, ViewContainerRef, ElementRef, OnInit } from '@angular/core';
import { Overlay } from '@angular/cdk/overlay';
export declare type NovoTooltipPosition = 'top' | 'right' | 'bottom' | 'left' | 'top-left' | 'bottom-left' | 'top-right' | 'bottom-right' | string;
export declare class TooltipDirective implements OnDestroy, OnInit {
    protected overlay: Overlay;
    private viewContainerRef;
    private elementRef;
    private POSITIONS;
    private DEFAULT_POSITIONS;
    tooltip: string;
    position: NovoTooltipPosition;
    type: string;
    size: string;
    bounce: string;
    noAnimate: boolean;
    rounded: boolean;
    always: boolean;
    active: boolean;
    preline: boolean;
    removeArrow: boolean;
    autoPosition: boolean;
    private portal;
    private overlayRef;
    constructor(overlay: Overlay, viewContainerRef: ViewContainerRef, elementRef: ElementRef);
    isPosition(position: string): boolean;
    isType(type: string): boolean;
    isSize(size: string): boolean;
    onMouseEnter(): void;
    onMouseLeave(): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
    private show;
    private hide;
    private getPosition;
}
