import { ChangeDetectorRef, ElementRef, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { DomSanitizer } from '@angular/platform-browser';
import { NovoLabelService } from '../../services/novo-label-service';
import { DatePickerSelectModes, modelTypes, rangeSelectModes } from './date-picker.types';
import * as i0 from "@angular/core";
export declare class NovoDatePickerElement implements ControlValueAccessor, OnInit {
    labels: NovoLabelService;
    private element;
    private cdr;
    private _sanitizer;
    minYear: string | number;
    maxYear: string | number;
    start: Date;
    end: Date;
    inline: boolean;
    weekStart: number;
    preselected: Date[];
    hideOverflowDays: boolean;
    hideFooter: boolean;
    onSelect: EventEmitter<any>;
    _mode: DatePickerSelectModes;
    _range: boolean;
    _weekRangeSelect: boolean;
    _numberOfMonths: number[];
    get numberOfMonths(): number;
    set numberOfMonths(value: number);
    get mode(): DatePickerSelectModes;
    set mode(value: DatePickerSelectModes);
    get range(): boolean;
    set range(value: boolean);
    get weekRangeSelect(): boolean;
    set weekRangeSelect(value: boolean);
    model: modelTypes;
    activeDate: Date;
    _selection: Date[];
    preview: Date[];
    startDateLabel: string;
    endDateLabel: string;
    rangeSelectMode: rangeSelectModes;
    _onChange: Function;
    _onTouched: Function;
    get selection(): Date[];
    set selection(value: Date[]);
    constructor(labels: NovoLabelService, element: ElementRef, cdr: ChangeDetectorRef, _sanitizer: DomSanitizer);
    ngOnInit(): void;
    updateView(date: any): void;
    updateSelection(selected: Date[], fireEvents?: boolean): void;
    eventData(date: Date): {
        year: number;
        month: any;
        day: any;
        date: Date;
    };
    fireSelect(): void;
    fireRangeSelect(): void;
    setToday(): void;
    toggleRangeSelect(range: rangeSelectModes): void;
    modelToSelection(model: modelTypes): void;
    writeValue(model: modelTypes): void;
    registerOnChange(fn: Function): void;
    registerOnTouched(fn: Function): void;
    static ɵfac: i0.ɵɵFactoryDef<NovoDatePickerElement, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<NovoDatePickerElement, "novo-date-picker", never, { "minYear": "minYear"; "maxYear": "maxYear"; "start": "start"; "end": "end"; "inline": "inline"; "weekStart": "weekStart"; "preselected": "preselected"; "hideOverflowDays": "hideOverflowDays"; "hideFooter": "hideFooter"; "numberOfMonths": "numberOfMonths"; "mode": "mode"; "range": "range"; "weekRangeSelect": "weekRangeSelect"; }, { "onSelect": "onSelect"; }, never, never>;
}
